<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\PriceHistory;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ─── OFFICE SUPPLIES ───
            [
                'name'          => 'HP 88A Black LaserJet Toner Cartridge',
                'brand'         => 'HP',
                'category'      => 'Office Supplies',
                'subcategory'   => 'Toner & Ink',
                'description'   => 'HP 88A Black Original LaserJet Toner Cartridge (CC388A) compatible with HP LaserJet Pro M1136, M1213nf, M1214nfh, M1216nfh, M1217nfw, P1007, P1008.',
                'image_url'     => 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=400',
                'gem_price'         => 1250.00,
                'gem_product_id'    => 'GEM-TON-88A-001',
                'gem_seller'        => 'TechSupplies India Pvt Ltd',
                'gem_bis_certified' => true,
                'gem_make_in_india' => false,
                'gem_msme_seller'   => true,
                'gem_delivery_days' => 5,
                'gem_warranty_months' => 6,
                'gem_seller_rating' => '4.3',
                'gem_stock'         => 200,
                'amazon_price'      => 1180.00,
                'amazon_product_id' => 'B00CTWPJH4',
                'amazon_seller'     => 'HP India Official',
                'amazon_rating'     => 4.4,
                'amazon_reviews'    => 8520,
                'amazon_delivery_days' => 2,
                'amazon_warranty_months' => 6,
                'amazon_bis_certified' => true,
                'amazon_shipping'   => 0,
                'flipkart_price'    => 1199.00,
                'flipkart_product_id' => 'TONHP88A001',
                'flipkart_seller'   => 'Flipkart Electronics',
                'flipkart_rating'   => 4.3,
                'flipkart_reviews'  => 4210,
                'flipkart_delivery_days' => 3,
                'flipkart_warranty_months' => 6,
                'flipkart_bis_certified' => true,
                'flipkart_shipping' => 0,
                'indiamart_price'   => 1100.00,
                'indiamart_seller'  => 'Delhi Printer Hub',
                'indiamart_moq'     => 5,
                'indiamart_delivery_days' => 7,
                'gst_percent'       => 18,
                'gem_premium_score' => 62,
                'specifications'    => ['Page Yield' => '1500 pages', 'Color' => 'Black', 'Compatibility' => 'HP LaserJet Pro', 'Type' => 'Original'],
            ],
            [
                'name'          => 'Godrej Interio Metal Office Chair',
                'brand'         => 'Godrej Interio',
                'category'      => 'Office Furniture',
                'subcategory'   => 'Chairs',
                'description'   => 'Ergonomic metal office chair with cushioned seat, back support, and armrests. BIS certified and suitable for government offices.',
                'image_url'     => 'https://images.unsplash.com/photo-1541558869434-2840d308329a?w=400',
                'gem_price'         => 8500.00,
                'gem_product_id'    => 'GEM-CHAIR-GOD-001',
                'gem_seller'        => 'Godrej Interio Official',
                'gem_bis_certified' => true,
                'gem_make_in_india' => true,
                'gem_msme_seller'   => false,
                'gem_delivery_days' => 10,
                'gem_warranty_months' => 24,
                'gem_seller_rating' => '4.6',
                'gem_stock'         => 50,
                'amazon_price'      => 9200.00,
                'amazon_product_id' => 'B08ABCD1234',
                'amazon_seller'     => 'Godrej Official Store',
                'amazon_rating'     => 4.2,
                'amazon_reviews'    => 1250,
                'amazon_delivery_days' => 5,
                'amazon_warranty_months' => 24,
                'amazon_bis_certified' => true,
                'amazon_shipping'   => 0,
                'flipkart_price'    => 8800.00,
                'flipkart_product_id' => 'CHAIRGOD001',
                'flipkart_seller'   => 'WS Retail',
                'flipkart_rating'   => 4.1,
                'flipkart_reviews'  => 870,
                'flipkart_delivery_days' => 7,
                'flipkart_warranty_months' => 24,
                'flipkart_bis_certified' => true,
                'flipkart_shipping' => 0,
                'indiamart_price'   => 7800.00,
                'indiamart_seller'  => 'Mumbai Office Mart',
                'indiamart_moq'     => 10,
                'indiamart_delivery_days' => 14,
                'gst_percent'       => 18,
                'gem_premium_score' => 82,
                'specifications'    => ['Material' => 'Metal + Fabric', 'Weight Capacity' => '120 kg', 'Armrests' => 'Yes', 'Wheels' => 'Yes', 'BIS Mark' => 'IS 4535'],
            ],
            // ─── IT EQUIPMENT ───
            [
                'name'          => 'Dell Latitude 3420 Laptop (Core i5, 8GB, 512GB SSD)',
                'brand'         => 'Dell',
                'category'      => 'IT Equipment',
                'subcategory'   => 'Laptops',
                'description'   => 'Dell Latitude 3420 business laptop with Intel Core i5-1135G7, 8GB DDR4, 512GB M.2 SSD, Windows 11 Pro, ideal for government procurement.',
                'image_url'     => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
                'gem_price'         => 52000.00,
                'gem_product_id'    => 'GEM-DELL-LAT-3420',
                'gem_seller'        => 'Dell India Pvt Ltd',
                'gem_bis_certified' => true,
                'gem_make_in_india' => true,
                'gem_msme_seller'   => false,
                'gem_delivery_days' => 7,
                'gem_warranty_months' => 36,
                'gem_seller_rating' => '4.7',
                'gem_stock'         => 30,
                'amazon_price'      => 54990.00,
                'amazon_product_id' => 'B09XYZ123',
                'amazon_seller'     => 'Dell India Official',
                'amazon_rating'     => 4.3,
                'amazon_reviews'    => 3200,
                'amazon_delivery_days' => 3,
                'amazon_warranty_months' => 12,
                'amazon_bis_certified' => true,
                'amazon_shipping'   => 0,
                'flipkart_price'    => 53499.00,
                'flipkart_product_id' => 'LAPTOPDELL001',
                'flipkart_seller'   => 'Flipkart Tech',
                'flipkart_rating'   => 4.2,
                'flipkart_reviews'  => 2100,
                'flipkart_delivery_days' => 4,
                'flipkart_warranty_months' => 12,
                'flipkart_bis_certified' => true,
                'flipkart_shipping' => 0,
                'indiamart_price'   => 49500.00,
                'indiamart_seller'  => 'IT Solutions Hub',
                'indiamart_moq'     => 5,
                'indiamart_delivery_days' => 10,
                'gst_percent'       => 18,
                'gem_premium_score' => 88,
                'specifications'    => ['Processor' => 'Intel Core i5-1135G7', 'RAM' => '8GB DDR4', 'Storage' => '512GB SSD', 'Display' => '14" FHD', 'OS' => 'Windows 11 Pro', 'Battery' => '42WHr'],
            ],
            [
                'name'          => 'Canon imageRUNNER 2206 Photocopier',
                'brand'         => 'Canon',
                'category'      => 'IT Equipment',
                'subcategory'   => 'Printers & Copiers',
                'description'   => 'Canon imageRUNNER 2206 A4 black & white multifunctional printer/copier. 22 ppm, network ready, suitable for high-volume government office use.',
                'image_url'     => 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=400',
                'gem_price'         => 38000.00,
                'gem_product_id'    => 'GEM-CANON-IR2206',
                'gem_seller'        => 'Canon India Pvt Ltd',
                'gem_bis_certified' => true,
                'gem_make_in_india' => false,
                'gem_msme_seller'   => false,
                'gem_delivery_days' => 10,
                'gem_warranty_months' => 12,
                'gem_seller_rating' => '4.5',
                'gem_stock'         => 15,
                'amazon_price'      => 41500.00,
                'amazon_product_id' => 'B0BXYZ9988',
                'amazon_seller'     => 'Canon Authorised',
                'amazon_rating'     => 4.1,
                'amazon_reviews'    => 890,
                'amazon_delivery_days' => 5,
                'amazon_warranty_months' => 12,
                'amazon_bis_certified' => true,
                'amazon_shipping'   => 0,
                'flipkart_price'    => 40200.00,
                'flipkart_product_id' => 'COPCANON001',
                'flipkart_seller'   => 'Flipkart Electronics',
                'flipkart_rating'   => 4.0,
                'flipkart_reviews'  => 430,
                'flipkart_delivery_days' => 7,
                'flipkart_warranty_months' => 12,
                'flipkart_bis_certified' => true,
                'flipkart_shipping' => 250,
                'indiamart_price'   => 35000.00,
                'indiamart_seller'  => 'Printer World India',
                'indiamart_moq'     => 2,
                'indiamart_delivery_days' => 14,
                'gst_percent'       => 18,
                'gem_premium_score' => 76,
                'specifications'    => ['Speed' => '22 ppm', 'Type' => 'Monochrome', 'Functions' => 'Print/Copy/Scan', 'Connectivity' => 'USB + Network', 'Paper Size' => 'A4', 'Duty Cycle' => '25000 pages/month'],
            ],
            // ─── STATIONERY ───
            [
                'name'          => 'Classmate Long Notebook (200 Pages, Pack of 6)',
                'brand'         => 'Classmate',
                'category'      => 'Stationery',
                'subcategory'   => 'Notebooks',
                'description'   => 'Classmate A4 long notebook, 200 ruled pages, hard cover. Pack of 6. Widely used in government schools and offices.',
                'image_url'     => 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400',
                'gem_price'         => 320.00,
                'gem_product_id'    => 'GEM-NB-CLS-200',
                'gem_seller'        => 'ITC Education Supplies',
                'gem_bis_certified' => false,
                'gem_make_in_india' => true,
                'gem_msme_seller'   => false,
                'gem_delivery_days' => 4,
                'gem_warranty_months' => 0,
                'gem_seller_rating' => '4.4',
                'gem_stock'         => 1000,
                'amazon_price'      => 299.00,
                'amazon_product_id' => 'B07ABCD001',
                'amazon_seller'     => 'ITC Official',
                'amazon_rating'     => 4.5,
                'amazon_reviews'    => 12000,
                'amazon_delivery_days' => 2,
                'amazon_warranty_months' => 0,
                'amazon_bis_certified' => false,
                'amazon_shipping'   => 0,
                'flipkart_price'    => 285.00,
                'flipkart_product_id' => 'NBCLSMT001',
                'flipkart_seller'   => 'Stationery World',
                'flipkart_rating'   => 4.4,
                'flipkart_reviews'  => 6700,
                'flipkart_delivery_days' => 3,
                'flipkart_warranty_months' => 0,
                'flipkart_bis_certified' => false,
                'flipkart_shipping' => 0,
                'indiamart_price'   => 260.00,
                'indiamart_seller'  => 'Bulk Stationery Depot',
                'indiamart_moq'     => 50,
                'indiamart_delivery_days' => 5,
                'gst_percent'       => 12,
                'gem_premium_score' => 45,
                'specifications'    => ['Pages' => '200', 'Size' => 'A4', 'Pack' => '6 Notebooks', 'Ruling' => 'Single Line', 'Cover' => 'Hard Bind'],
            ],
            // ─── CLEANING SUPPLIES ───
            [
                'name'          => 'Dettol Original Liquid Handwash (750ml, Pack of 3)',
                'brand'         => 'Dettol',
                'category'      => 'Cleaning & Hygiene',
                'subcategory'   => 'Handwash',
                'description'   => 'Dettol Original antibacterial liquid handwash, 750ml pack of 3. Used extensively in government hospitals, schools and offices.',
                'image_url'     => 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=400',
                'gem_price'         => 640.00,
                'gem_product_id'    => 'GEM-DETTOL-HW-750',
                'gem_seller'        => 'Reckitt Benckiser India',
                'gem_bis_certified' => true,
                'gem_make_in_india' => true,
                'gem_msme_seller'   => false,
                'gem_delivery_days' => 4,
                'gem_warranty_months' => 18,
                'gem_seller_rating' => '4.8',
                'gem_stock'         => 5000,
                'amazon_price'      => 598.00,
                'amazon_product_id' => 'B08DTTL001',
                'amazon_seller'     => 'Reckitt Official',
                'amazon_rating'     => 4.7,
                'amazon_reviews'    => 24000,
                'amazon_delivery_days' => 1,
                'amazon_warranty_months' => 18,
                'amazon_bis_certified' => true,
                'amazon_shipping'   => 0,
                'flipkart_price'    => 610.00,
                'flipkart_product_id' => 'HWDET750001',
                'flipkart_seller'   => 'Supermart',
                'flipkart_rating'   => 4.6,
                'flipkart_reviews'  => 15000,
                'flipkart_delivery_days' => 2,
                'flipkart_warranty_months' => 18,
                'flipkart_bis_certified' => true,
                'flipkart_shipping' => 0,
                'indiamart_price'   => 560.00,
                'indiamart_seller'  => 'Hygiene Wholesale Co.',
                'indiamart_moq'     => 24,
                'indiamart_delivery_days' => 5,
                'gst_percent'       => 18,
                'gem_premium_score' => 55,
                'specifications'    => ['Volume' => '750ml x 3', 'Type' => 'Antibacterial', 'Fragrance' => 'Original', 'Certification' => 'BIS IS 17334'],
            ],
            // ─── ELECTRONICS ───
            [
                'name'          => 'Luminous Zelio+ 1100 Home UPS Inverter',
                'brand'         => 'Luminous',
                'category'      => 'Electrical & Power',
                'subcategory'   => 'UPS & Inverters',
                'description'   => 'Luminous Zelio+ 1100 pure sine wave home UPS/inverter with LCD display, suitable for government offices and small establishments. BIS certified.',
                'image_url'     => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
                'gem_price'         => 7200.00,
                'gem_product_id'    => 'GEM-LUM-ZELIO-1100',
                'gem_seller'        => 'Luminous Power Tech',
                'gem_bis_certified' => true,
                'gem_make_in_india' => true,
                'gem_msme_seller'   => false,
                'gem_delivery_days' => 5,
                'gem_warranty_months' => 24,
                'gem_seller_rating' => '4.6',
                'gem_stock'         => 80,
                'amazon_price'      => 7850.00,
                'amazon_product_id' => 'B09LUMZ001',
                'amazon_seller'     => 'Luminous Official',
                'amazon_rating'     => 4.5,
                'amazon_reviews'    => 5600,
                'amazon_delivery_days' => 3,
                'amazon_warranty_months' => 24,
                'amazon_bis_certified' => true,
                'amazon_shipping'   => 0,
                'flipkart_price'    => 7599.00,
                'flipkart_product_id' => 'UPSLUM1100',
                'flipkart_seller'   => 'Omnitech Retail',
                'flipkart_rating'   => 4.4,
                'flipkart_reviews'  => 3100,
                'flipkart_delivery_days' => 4,
                'flipkart_warranty_months' => 24,
                'flipkart_bis_certified' => true,
                'flipkart_shipping' => 0,
                'indiamart_price'   => 6800.00,
                'indiamart_seller'  => 'Power Solutions Pvt',
                'indiamart_moq'     => 3,
                'indiamart_delivery_days' => 7,
                'gst_percent'       => 18,
                'gem_premium_score' => 80,
                'specifications'    => ['Capacity' => '1100VA', 'Type' => 'Pure Sine Wave', 'Display' => 'LCD', 'Battery' => '12V 100Ah (Not included)', 'BIS' => 'IS 16242'],
            ],
            [
                'name'          => 'Honeywell HAC35M2 Air Purifier',
                'brand'         => 'Honeywell',
                'category'      => 'Electrical & Power',
                'subcategory'   => 'Air Purifiers',
                'description'   => 'Honeywell HAC35M2 HEPA + Carbon filter air purifier. Suitable for rooms up to 388 sq ft. Used in government hospitals and conference rooms.',
                'image_url'     => 'https://images.unsplash.com/photo-1545259742-f1f6c2c08c22?w=400',
                'gem_price'         => 19800.00,
                'gem_product_id'    => 'GEM-HON-HAC35M2',
                'gem_seller'        => 'Honeywell India',
                'gem_bis_certified' => true,
                'gem_make_in_india' => false,
                'gem_msme_seller'   => false,
                'gem_delivery_days' => 7,
                'gem_warranty_months' => 12,
                'gem_seller_rating' => '4.4',
                'gem_stock'         => 25,
                'amazon_price'      => 17999.00,
                'amazon_product_id' => 'B09HNWL001',
                'amazon_seller'     => 'Honeywell Authorised',
                'amazon_rating'     => 4.2,
                'amazon_reviews'    => 2300,
                'amazon_delivery_days' => 3,
                'amazon_warranty_months' => 12,
                'amazon_bis_certified' => true,
                'amazon_shipping'   => 0,
                'flipkart_price'    => 18499.00,
                'flipkart_product_id' => 'AIRHON35M001',
                'flipkart_seller'   => 'Flipkart Electronics',
                'flipkart_rating'   => 4.1,
                'flipkart_reviews'  => 1100,
                'flipkart_delivery_days' => 5,
                'flipkart_warranty_months' => 12,
                'flipkart_bis_certified' => true,
                'flipkart_shipping' => 0,
                'indiamart_price'   => null,
                'indiamart_seller'  => null,
                'gst_percent'       => 18,
                'gem_premium_score' => 42,
                'specifications'    => ['CADR' => '200 m³/h', 'Filter' => 'HEPA + Carbon', 'Room Size' => '388 sq ft', 'Noise' => '22-50 dB', 'Power' => '45W'],
            ],
        ];

        foreach ($products as $data) {
            $product = Product::create($data);

            // Generate 90 days of price history
            $platforms = [
                'gem'      => $data['gem_price'] ?? null,
                'amazon'   => $data['amazon_price'] ?? null,
                'flipkart' => $data['flipkart_price'] ?? null,
            ];

            foreach ($platforms as $platform => $currentPrice) {
                if (!$currentPrice) continue;
                for ($i = 89; $i >= 0; $i--) {
                    // Simulate realistic price fluctuations
                    $fluctuation = 1 + ((mt_rand(-8, 8) / 100));
                    // Add occasional spikes/dips
                    if ($i % 30 === 0) $fluctuation = 1 + ((mt_rand(-15, 15) / 100));
                    $price = round($currentPrice * $fluctuation, 2);
                    PriceHistory::create([
                        'product_id'    => $product->id,
                        'platform'      => $platform,
                        'price'         => max($price, $currentPrice * 0.7),
                        'recorded_date' => Carbon::today()->subDays($i),
                    ]);
                }
            }
        }
    }
}
