<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Comparative Statement Report - NexBuy</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"/>
    <style>
        :root {
            --primary: #7C3AED;
            --text-main: #F8FAFC;
            --bg-base: #030014;
            --glass-border: rgba(255, 255, 255, 0.1);
        }
        body {
            font-family: 'Plus Jakarta Sans', sans-serif;
            background: var(--bg-base);
            color: var(--text-main);
            margin: 0; padding: 2rem;
            line-height: 1.5;
        }
        .report-header {
            text-align: center; margin-bottom: 3rem;
            border-bottom: 2px solid var(--glass-border); padding-bottom: 2rem;
        }
        .report-header h1 {
            font-size: 2rem; font-weight: 700; margin: 0 0 0.5rem; color: white;
        }
        .report-header p { margin: 0; color: #94A3B8; font-size: 0.95rem; }
        
        .meta-info {
            display: flex; justify-content: space-between; margin-bottom: 2rem;
            background: rgba(255,255,255,0.02); border: 1px solid var(--glass-border); padding: 1.5rem; border-radius: 12px;
        }
        .meta-group { display: flex; flex-direction: column; }
        .meta-label { font-size: 0.75rem; text-transform: uppercase; color: #94A3B8; font-weight: 600; letter-spacing: 1px; }
        .meta-value { font-size: 1.1rem; font-weight: 700; color: white; }
        
        table {
            width: 100%; border-collapse: collapse; margin-bottom: 2rem;
            background: rgba(255,255,255,0.02); border: 1px solid var(--glass-border); border-radius: 12px; overflow: hidden;
        }
        th, td {
            padding: 1.25rem; text-align: left; border-bottom: 1px solid var(--glass-border);
        }
        th { background: rgba(0,0,0,0.4); font-weight: 600; color: #94A3B8; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.5px; }
        tr:last-child td { border-bottom: none; }
        
        .btn {
            display: inline-flex; align-items: center; gap: 0.5rem; background: var(--primary); color: white; border: none;
            padding: 0.8rem 2rem; border-radius: 50px; font-weight: 600; font-family: inherit; font-size: 1rem; cursor: pointer; text-decoration: none;
        }
        
        /* Print Styles */
        @media print {
            body { background: white; color: black; padding: 0; }
            .report-header h1 { color: black; }
            .report-header p, .meta-label { color: #555; }
            .meta-value { color: black; }
            .meta-info { border: 1px solid #ccc; background: transparent; }
            table { border: 1px solid #ccc; background: transparent; }
            th { background: #f0f0f0; color: black; border-bottom: 2px solid #ccc; }
            td { border-bottom: 1px solid #ddd; }
            .no-print { display: none !important; }
        }
    </style>
</head>
<body>
    <div style="max-width: 1000px; margin: 0 auto;">
        
        <div class="report-header">
            <h1>Comparative Statement (CS) Matrix</h1>
            <p>Generated by NexBuy Intelligence Engine v2.0</p>
        </div>
        
        <div class="meta-info">
            <div class="meta-group">
                <span class="meta-label">Date Generated</span>
                <span class="meta-value">{{ date('d M Y, h:i A') }}</span>
            </div>
            <div class="meta-group">
                <span class="meta-label">Reference ID</span>
                <span class="meta-value">CS-{{ strtoupper(Str::random(8)) }}</span>
            </div>
            <div class="meta-group">
                <span class="meta-label">Items Analyzed</span>
                <span class="meta-value">{{ $products->count() }}</span>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Item Specification</th>
                    <th>GeM Cost</th>
                    <th>Amazon Cost</th>
                    <th>Flipkart Cost</th>
                    <th>Recommended Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($products as $p)
                <tr>
                    <td>
                        <div style="font-weight: 600; font-size: 0.95rem; margin-bottom: 0.2rem;">{{ $p->name }}</div>
                        <div style="font-size: 0.8rem; color: #94A3B8;">{{ $p->brand }} · {{ $p->category }}</div>
                    </td>
                    <td style="font-weight: 600;">{{ $p->gem_price ? '₹'.number_format($p->gem_price, 0) : 'N/A' }}</td>
                    <td>{{ $p->amazon_price ? '₹'.number_format($p->amazon_price, 0) : 'N/A' }}</td>
                    <td>{{ $p->flipkart_price ? '₹'.number_format($p->flipkart_price, 0) : 'N/A' }}</td>
                    <td>
                        <span style="display: inline-block; padding: 0.3rem 0.8rem; background: rgba(16,185,129,0.1); color: #10B981; border: 1px solid rgba(16,185,129,0.3); border-radius: 50px; font-weight: 700; font-size: 0.85rem;">
                            Procure via {{ $p->lowest_platform }}
                        </span>
                        <div style="font-size: 0.75rem; color: #94A3B8; margin-top: 0.4rem;">Optimized rate: ₹{{ number_format($p->lowest_price, 0) }}</div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div style="margin-top: 4rem; display: flex; justify-content: space-between; align-items: flex-end;">
            <div>
                <p style="font-size: 0.85rem; color: #94A3B8; max-width: 400px;">
                    This document is generated by automated market intelligence gathering and serves as a technical aid for procurement justification.
                </p>
            </div>
            <div style="text-align: center; width: 200px;">
                <div style="border-bottom: 1px solid #94A3B8; margin-bottom: 0.5rem; height: 40px;"></div>
                <div style="font-size: 0.85rem; font-weight: 600;">Authorized Signature</div>
            </div>
        </div>

        <div class="no-print" style="margin-top: 4rem; text-align: center;">
            <button onclick="window.print()" class="btn">🖨️ Execute Print / Export PDF</button>
            <a href="{{ url()->previous() }}" style="display: block; margin-top: 1rem; color: #94A3B8; text-decoration: none; font-size: 0.9rem;">Return to Dashboard</a>
        </div>
        
    </div>
</body>
</html>
