<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class AiProcurementService
{
    /**
     * AI Product Matcher
     * Semantically compares a GeM product with an Amazon/Flipkart product
     * to determine if they are the exact same item despite title differences.
     */
    public function matchProducts(array $gemProduct, array $commercialProduct): array
    {
        // Mocking the AI response for demonstration.
        // In production, this would call Google Gemini API:
        // Http::withToken(env('GEMINI_API_KEY'))->post('...', ['prompt' => ...]);

        $score = rand(75, 99);
        $isMatch = $score > 85;

        $analysis = [
            'Match Score: ' . $score . '%',
            'Processor: Exact Match (Intel Core i5-1235U)',
            'RAM: Exact Match (8GB DDR4)',
            'Storage: Exact Match (512GB NVMe SSD)',
            'Title Discrepancy: Commercial title includes marketing terms not present in GeM title.'
        ];

        return [
            'is_match' => $isMatch,
            'confidence_score' => $score,
            'analysis' => $analysis,
            'recommendation' => $isMatch ? 'Proceed with price comparison. These are identical products.' : 'Caution: Specifications differ. Not a direct comparison.',
        ];
    }

    /**
     * Automated RFP/Bid Generation
     * Drafts a Request for Proposal based on the best specifications.
     */
    public function generateRfp(array $specifications, string $departmentName): string
    {
        // Mocking the generated RFP text.
        $date = now()->format('d F Y');
        $specsHtml = '<ul>';
        foreach ($specifications as $key => $value) {
            $specsHtml .= "<li><strong>" . ucfirst($key) . ":</strong> $value</li>";
        }
        $specsHtml .= '</ul>';

        return "
            <div style='font-family: serif; line-height: 1.6;'>
                <h2 style='text-align: center; text-transform: uppercase;'>Request for Proposal (RFP)</h2>
                <p style='text-align: right;'><strong>Date:</strong> {$date}</p>
                <p><strong>Department:</strong> {$departmentName}</p>
                <p><strong>Subject:</strong> Procurement of Goods as per Technical Specifications</p>
                <hr>
                <p>Sealed bids are invited from eligible and qualified bidders for the supply of the following items meeting the exact technical specifications listed below:</p>
                <h3>1. Technical Specifications Required:</h3>
                {$specsHtml}
                <h3>2. Compliance Requirements:</h3>
                <ul>
                    <li>The bidder must be registered on the Government e-Marketplace (GeM).</li>
                    <li>Items must be Make in India certified.</li>
                    <li>A minimum of 1 year comprehensive warranty must be provided.</li>
                </ul>
                <p><strong>Deadline for Submission:</strong> " . now()->addDays(14)->format('d F Y') . "</p>
                <p><em>Generated by NexBuy AI Procurement Assistant.</em></p>
            </div>
        ";
    }

    /**
     * OCR for Quotation Comparison
     * Extracts items and prices from an uploaded scanned PDF/Image quotation.
     */
    public function extractQuotationData($file): array
    {
        // Mocking OCR extraction.
        // In production, this would use Google Cloud Vision API or AWS Textract.
        
        return [
            'vendor_name' => 'ABC Electronics Pvt Ltd',
            'quotation_date' => now()->subDays(2)->format('Y-m-d'),
            'items' => [
                [
                    'description' => 'Dell Vostro 15 Laptop i5 12th Gen',
                    'quantity' => 5,
                    'unit_price' => 45000,
                    'total_price' => 225000,
                    'tax_percent' => 18
                ],
                [
                    'description' => 'Logitech Wireless Mouse M235',
                    'quantity' => 5,
                    'unit_price' => 650,
                    'total_price' => 3250,
                    'tax_percent' => 18
                ]
            ],
            'grand_total' => 269335 // (225000+3250) + 18% GST
        ];
    }
}
